export const INITIALIZE = 'MULTISIG:INITIALIZE';
export const SET_INITIALIZED = 'MULTISIG:SET_INITIALIZED';
export const SET_TRANSACTIONS = 'MULTISIG:SET_TRANSACTIONS';
export const SET_TRANSACTIONS_LOADING = 'MULTISIG:SET_TRANSACTIONS_LOADING';
